# Generated by Django 4.2 on 2024-12-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssf_admin', '0002_premiumprice_standardprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('whatsapp', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('facebook', models.CharField(max_length=150)),
            ],
        ),
    ]
